// console.log([0] == false)
// console.log(![1] === false)
// console.log(Number('10px'))
// console.log(parseInt('10px'))
// console.log(Number(null))
// console.log(Number(undefined))
// console.log(parseFloat('10.251.26'))
// console.log(parseFloat('10.25.26'))
// console.log(2.6 + 1 + typeof NaN)
// console.log(3 + [1,2])
// console.log(Number(false))
// console.log(isNaN(null))
// console.log(isNaN(undefined))
// console.log(10+NaN)
// console.log('aaa'+ {})
// console.log('aaa'+ [])
let n = "10"
// console.log(+n)
// console.log(++n)
console.log(n++)
console.log(n)
console.log(({})+0)
console.log(0+{})
console.log([1,2,3].valueOf())
console.log([1,2,3].toString())